### ISSUE TITLE
Missing schematics

### ISSUE THREAD

**Issue by stomascik** [ArrowElectronicsESC/BluetoothXpressShield#2]
Hello,

can you please release .pdf schematics of this board? In the Design Documents/BGX13_Shield_V1_0.zip are assembly files only.

Thank you.
Slavomir Tomascik

**Comment by ebeppler03** [comment]
Slavomir - I have attached them here and they will be added to the next Github update.
[BGX_Shield_V1_0.pdf](https://github.com/ArrowElectronicsESC/BluetoothXpressShield/files/3108199/BGX_Shield_V1_0.pdf)

**Comment by microwattbott** [comment]
Dear Sir,
     Thanks.  I needed that.  I cannot seem to get any
signal/voltage/current from the LED screw block.  The BLE works great
mostly.  I had a led and resistor in series connected to red and ground and
the default is totem mode on that output.   No Joy.  it did not light up
and my VOM could not detect any signal.  The onboard LEDs flash perfectly.
Are there a known problems with the  PCA9633 output drive on the
SLASH1000A?  I set the .ino Global variable OUTPUT_MODE to 1 and it made no
difference to detecting signal at the LED block.   I added the following
code to try and get the PCA9633 to send the signal to the external LED
driver.  Still no joy.
  if (!OUTPUT_MODE)  {    // could not get a single led to light
                          //on PWM output for lighting controller
    dimmer->onBoardMode();  // !! deduced solution :  independent
               // power supply required for "lighting controller"
              //  due to "open drain" congifuration  * change
                 // made from totem-pole config
  } else   {      // looked at this to see if program can get
                              // control of the invert verses
    dimmer->outputMode();   // non-invert parameter for PCA9633
                         // enable lighting controller output.
 }
Can you please point me in the right direction?

Thanks.

**Comment by ebeppler03** [comment]
Hi Microwattbott,

FYI the Screw block terminal is a 0-10V dimming controller designed for use with a system like this: https://www.arrow.com/en/products/ess030w-0500-56/energy-recovery-products-erp

The output is not driven, but is rather a current sinking output. This is a very common control system used in lighting systems. More info can be found here: https://en.wikipedia.org/wiki/0-10_V_lighting_control

Thanks!

**Comment by microwattbott** [comment]
thank you, the wiki link for 0-10 V lighting control
<https://en.wikipedia.org/wiki/0-10_V_lighting_control> will be very useful.
I am wanting to test the output block without spending $40.00 for the extra
hardware.  I am going to check if my flourescent fixtures to see if I have
one that is dimmable with the 0-10 V control.   Thanks again for the wiki
link and the circuit *schematic *diagram.

**Comment by microwattbott** [comment]
A little web research led me to an easy to understand home brew lighting control circuit that should be usable with the SLASH1000A terminal block OR just an Arduino.  Here is the link : [https://maker.pro/arduino/projects/arduino-lamp-dimmer](https://maker.pro/arduino/projects/arduino-lamp-dimmer).  
Of course, four of that circuit would be needed to use the full RGBW capabilities or the SLASH1000A.
