### ISSUE TITLE
CHALLENGE OF FINDING THE INFO WHEN USING THE SLASH1000A

### ISSUE THREAD

**Issue by microwattbott** [ArrowElectronicsESC/BluetoothXpressShield#3]
Yes, I know it is the .pdf includes a link to the github.  BUT the .pdf has been un-linked from the arrow.com page for the board.
This is what I need:     Some where on this github page AND in the (all) zipped files MUST be included the device's name:  SLASH1000A.   Is there any bonafide reason for creating this firewall of secrecy?  The github search engine should direct me to these pages when I query it for SLASH1000A.  My PC should find the zip file on my harddrive when I look for SLASH1000A.

**Comment by ebeppler03** [comment]
Hi microwattbott - Sorry for the confusion - The github link has been re-added to the SLASH1000A page on Arrow.com. Unfortunately the 'SLASH1000A' Name was decided on fairly late in the process so the name isn't on all the materials - A readMe will be added to the next update to help mitigate this and provide installation instructions for the library.
